services:
  - type: web
    name: flask-wkhtmltopdf-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y wkhtmltopdf && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
